title: Smoovement Dev Journal
description: Daily build log for the Smoovement LoL Tracker
theme: minima
url: "https://shandanpy.github.io"
baseurl: "/Smoovement"   # note the capital S, must match repo name
