name: Add Epics to Roadmap

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-roadmap:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'epic') && vars.AUTOMATION_ENABLED == '1'
    
    steps:
      - name: Add Epic to Roadmap
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          script: |
            // First, get the project's global node ID
            const projectQuery = await github.graphql(`
              query($org: String!, $number: Int!) {
                organization(login: $org) {
                  projectV2(number: $number) {
                    id
                  }
                }
              }
            `, {
              org: '${{ vars.ORG_LOGIN }}',
              number: parseInt('${{ vars.ORG_ROADMAP_NUMBER }}')
            });
            
            const projectId = projectQuery.organization.projectV2.id;
            
            // Now add the issue to the project
            const { data } = await github.graphql(`
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {
                  projectId: $projectId,
                  contentId: $contentId
                }) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId: projectId,
              contentId: context.payload.issue.node_id
            });
            
            console.log('Successfully added issue to roadmap:', data.addProjectV2ItemById.item.id);
