name: Add Tasks to Execution

on:
  issues:
    types: [opened]

jobs:
  add-to-execution:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.issue.labels.*.name, 'epic') && vars.AUTOMATION_ENABLED == '1' }}
    
    steps:
      - name: Add Task to Execution Board
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN || secrets.ORG_PROJECT_TOKEN }}
          script: |
            try {
              // First, get the project's global node ID
              const projectQuery = await github.graphql(`
                query($org: String!, $number: Int!) {
                  organization(login: $org) {
                    projectV2(number: $number) {
                      id
                    }
                  }
                }
              `, {
                org: '${{ vars.ORG_LOGIN }}',
                number: parseInt('${{ vars.REPO_EXEC_NUMBER }}')
              });
              
              const projectId = projectQuery.organization.projectV2.id;
              
              // Now add the issue to the project
              const { data } = await github.graphql(`
                mutation($projectId: ID!, $contentId: ID!) {
                  addProjectV2ItemById(input: {
                    projectId: $projectId,
                    contentId: $contentId
                  }) {
                    item {
                      id
                    }
                  }
                }
              `, {
                projectId: projectId,
                contentId: context.payload.issue.node_id
              });
              
              console.log('Successfully added issue to execution board:', data.addProjectV2ItemById.item.id);
              console.log('Issue #' + context.payload.issue.number + ' added to Execution project');
              
            } catch (error) {
              console.error('Failed to add issue to execution board:', error);
              console.error('Error details:', error.message);
              
              // Check if it's a permissions issue
              if (error.message.includes('Resource not accessible by integration')) {
                console.error('Token permissions issue. Please check that the token has project write access.');
              }
              
              // Re-throw to fail the workflow
              throw error;
            }
