name: Add Tasks to Execution

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  add_task_to_execution:
    if: ${{ vars.AUTOMATION_ENABLED == '1' && github.event.issue != null && !contains(github.event.issue.labels.*.name, 'epic') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Resolve user project ID (Execution)
        id: proj
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          script: |
            const login = process.env.ORG_LOGIN;
            const number = parseInt(process.env.REPO_EXEC_NUMBER, 10);
            const q = `query($login:String!, $number:Int!){
              user(login:$login){
                projectV2(number:$number){ id }
              }
            }`;
            const r = await github.graphql(q, { login, number });
            if (!r.user?.projectV2?.id) {
              core.setFailed(`Execution project not found for user ${login} #${number}`);
              return;
            }
            core.setOutput('projectId', r.user.projectV2.id);

      - name: Add issue to Execution
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          script: |
            const projectId = '${{ steps.proj.outputs.projectId }}';
            const contentId = '${{ github.event.issue.node_id }}';
            const m = `mutation($projectId:ID!, $contentId:ID!){
              addProjectV2ItemById(input:{projectId:$projectId, contentId:$contentId}){ item { id } }
            }`;
            await github.graphql(m, { projectId, contentId });
    env:
      ORG_LOGIN: ${{ vars.ORG_LOGIN }}
      REPO_EXEC_NUMBER: ${{ vars.REPO_EXEC_NUMBER }}
